### ISSUE TITLE
Missing LICENSE.md file

### ISSUE THREAD

**Issue by Jeidoz** [Fantoom/WallEngine#1]
Hi, you have the wrong link to the [**LICENSE.md**](https://github.com/Fantoom/WallEngine/blob/master/LICENSE.md) file in your [**README.md**](https://github.com/Fantoom/WallEngine/blob/master/README.md). Please, [add a license file](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) or remove that readme part.

**Comment by Fantoom** [comment]
LICENSE.md has already been in the repository, the link to the file was borken, I have fixed it in #095b9cf
